services:
  db:
    image: postgres:17
    container_name: postgres_db_rent-machine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rent-machine
    ports:
      - "5432:5432"
